name: Daily Cloudflare R2 Sync

on:
  workflow_dispatch:  # 수동 실행 가능

# 동시 실행 방지
concurrency:
  group: daily-r2-sync
  cancel-in-progress: true

permissions:
  contents: read
  actions: read

env:
  # Git 저장소 설정
  GIT_REPO_URL: https://github.com/kadragon/KNUE-Policy-Hub.git
  GIT_BRANCH: main

  # Cloudflare R2 설정
  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
  CLOUDFLARE_R2_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_R2_ACCESS_KEY_ID }}
  CLOUDFLARE_R2_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_R2_SECRET_ACCESS_KEY }}
  CLOUDFLARE_R2_BUCKET: ${{ secrets.CLOUDFLARE_R2_BUCKET }}
  CLOUDFLARE_R2_ENDPOINT: ${{ secrets.CLOUDFLARE_R2_ENDPOINT }}

jobs:
  cloudflare-r2-sync:
    name: Cloudflare R2 Sync
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Prepare uv cache directories
        run: |
          mkdir -p ~/.cache/uv
          mkdir -p ~/.local/share/uv

      - name: Cache uv dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
            ~/.local/share/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('**/uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Install dependencies
        run: |
          uv sync --no-dev
          uv pip install -e .

      - name: Create logs directory
        run: mkdir -p logs

      - name: Run Cloudflare R2 sync
        run: |
          uv run python -m src.sync_pipeline sync-cloudflare-r2
        timeout-minutes: 30
        env:
          LOG_FILE: logs/cloudflare-r2-sync.log

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cloudflare-r2-sync-logs-${{ github.run_number }}
          path: logs/
          retention-days: 7
          if-no-files-found: ignore
